worker_processes 1;
error_log logs/nginx-error.log;
pid logs/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    client_max_body_size 20m;
    access_log logs/nginx-access.log;
    client_body_temp_path tmp/client_body;
    proxy_temp_path tmp/proxy;
    fastcgi_temp_path tmp/fastcgi;
    uwsgi_temp_path tmp/uwsgi;
    scgi_temp_path tmp/scgi;

    server {
        listen 18080;
        server_name _;
        root fronted/dist;
        index index.html;

        location /api/ {
            proxy_pass http://127.0.0.1:18081/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Cookie $http_cookie;
            proxy_cookie_path / /;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
