USE campus_reimburse;
SET FOREIGN_KEY_CHECKS=0;
DELETE FROM invoice_occupation;
DELETE FROM invoice_ocr_result;
DELETE FROM claim_expense_file;
DELETE FROM claim_expense_line;
DELETE FROM claim_file_material;
DELETE FROM claim_invoice;
DELETE FROM claim_file;
DELETE FROM claim_flow_log;
DELETE FROM claim_todo;
DELETE FROM claim_revision;
DELETE FROM travel_person;
DELETE FROM travel_leg;
DELETE FROM travel_claim;
DELETE FROM travel_apply;
DELETE FROM claim_form;
DELETE FROM sys_notify;
DELETE FROM sys_audit_log;
DELETE FROM job_task;
DELETE FROM data_export;
DELETE FROM data_import_item;
DELETE FROM data_import;
DELETE FROM user_guide_step;
DELETE FROM user_guide_progress;
DELETE FROM user_feature_usage;
DELETE FROM api_idempotency;
SET FOREIGN_KEY_CHECKS=1;
